name: Release

on:
  release:
    types: [ published ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: MCJack123/ghaction-Generate-Release-Hashes@v1
      with:
        hash-type: md5
        file-name: hashes.txt
    - uses: actions/upload-artifact@v2
      with:
        path: hashes.txt

    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: hashes.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}